eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservices:
  employee-service:
    endpoints:
      endpoint:
        uri: http://Employee-Department-Service/department/employeeId/
  employee-rating-service:
    endpoints:
      endpoint:
        uri: http://Employee-Rating-Service/rating/employeeId/  
