eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    
microservices:
  employee-department-service:
    endpoints:
      endpoint:
        uri: http://Employee-Department-Service/department/employeeId/
  employee-rating-service:
    endpoints:
      endpoint:
        uri: http://Employee-Rating-Service/rating/employeeId/  
